# Generated by Django 5.1 on 2024-09-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=255)),
                ('placas', models.CharField(max_length=60)),
                ('combustible', models.CharField(choices=[('GASOLINE', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Eléctrico')], default='GASOLINE', max_length=30)),
                ('valor_original', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GastosVehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_combustible', models.FloatField()),
                ('monto', models.FloatField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('conductor', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyectos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.vehiculos')),
            ],
        ),
    ]
