# Generated by Django 5.1 on 2024-09-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_vehiculos_color_vehiculos_marca'),
        ('proyectos', '0005_alter_proyectos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosvehiculos',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_vehiculos', to='proyectos.proyectos'),
        ),
        migrations.AlterField(
            model_name='gastosvehiculos',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='gastos.vehiculos'),
        ),
    ]
