# Generated by Django 5.1 on 2024-09-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_alter_gastosvehiculos_proyecto_and_more'),
        ('proyectos', '0005_alter_proyectos_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('monto_concepto', models.FloatField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=80)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_generales', to='proyectos.proyectos')),
            ],
        ),
    ]
