# Generated by Django 5.1 on 2024-09-10 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_gastosgenerales'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosgenerales',
            name='comprador',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 0, 38, 3, 736752, tzinfo=datetime.timezone.utc)),
        ),
    ]
