# Generated by Django 5.1 on 2024-09-10 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gastosgenerales_comprador_gastosgenerales_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 0, 48, 4, 803129, tzinfo=datetime.timezone.utc)),
        ),
    ]
