# Generated by Django 5.1 on 2024-09-10 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_alter_gastosgenerales_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 19, 31, 6, 464337, tzinfo=datetime.timezone.utc)),
        ),
    ]
