# Generated by Django 5.1 on 2024-09-11 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_alter_gastosgenerales_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 18, 45, 13, 279135, tzinfo=datetime.timezone.utc)),
        ),
    ]
