# Generated by Django 5.1 on 2024-09-14 02:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0012_alter_gastosgenerales_fecha'),
        ('proyectos', '0007_ingresos_concepto_ingresos_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 2, 27, 49, 622807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='GastosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('comprador', models.CharField(default='', max_length=255)),
                ('tiempo_renta', models.CharField(choices=[('RENTA_MENSUAL', 'renta mensual'), ('RENTA_SEMANAL', 'renta semanal'), ('RENTA_DIARIA', 'renta diaria'), ('PROPIEDAD', 'Propiedad')], default='RENTA_MENSUAL', max_length=100)),
                ('monto_concepto', models.FloatField()),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=80)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 9, 14, 2, 27, 49, 622807, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_equipos', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina', models.FloatField()),
                ('imss', models.FloatField()),
                ('infonavit', models.FloatField()),
                ('isn', models.FloatField()),
                ('isr', models.FloatField()),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 9, 14, 2, 27, 49, 622807, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_mano_obra', to='proyectos.proyectos')),
            ],
        ),
        migrations.CreateModel(
            name='GastosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_material', models.CharField(max_length=255)),
                ('comprador', models.CharField(default='', max_length=255)),
                ('monto', models.FloatField()),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=80)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 9, 14, 2, 27, 49, 622807, tzinfo=datetime.timezone.utc))),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_materiales', to='proyectos.proyectos')),
            ],
        ),
    ]
