# Generated by Django 5.1 on 2024-09-14 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0013_alter_gastosgenerales_fecha_gastosequipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosmanoobra',
            name='monto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gastosequipos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 25, 31, 568909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 25, 31, 568909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmanoobra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 25, 31, 568909, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmateriales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 25, 31, 568909, tzinfo=datetime.timezone.utc)),
        ),
    ]
