# Generated by Django 5.1 on 2024-09-14 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0014_gastosmanoobra_monto_alter_gastosequipos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosequipos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 56, 48, 884005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 56, 48, 884005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmanoobra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 56, 48, 884005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmateriales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 3, 56, 48, 884005, tzinfo=datetime.timezone.utc)),
        ),
    ]
