# Generated by Django 5.1 on 2024-09-21 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0015_alter_gastosequipos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosequipos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 20, 1, 32, 20344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosgenerales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 20, 1, 32, 19344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmanoobra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 20, 1, 32, 20344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gastosmateriales',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 20, 1, 32, 19344, tzinfo=datetime.timezone.utc)),
        ),
    ]
