# Generated by Django 5.1 on 2024-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
