# Generated by Django 5.1 on 2024-09-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyectos_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
