# Generated by Django 5.1 on 2024-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_proyectos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
