# Generated by Django 5.1 on 2024-09-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_proyectos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
