# Generated by Django 5.1 on 2024-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='concepto',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='referencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
